---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  # "namespace" omitted since ClusterRoles are not namespaced
  name: pod-perm
rules:
  - apiGroups: ['']
    resources: ['pods']
    verbs: ['*']
