---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: pod-perm
subjects:
  - kind: ServiceAccount
    name: xyz
    namespace: default
    apiGroup: ""
roleRef:
  kind: ClusterRole
  name: pod-perm
  apiGroup: rbac.authorization.k8s.io
