apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: xyz
  name: in-cls
spec:
  replicas: 2
  selector:
    matchLabels:
      app: xyz
  template:
    metadata:
      labels:
        app: xyz
    spec:
      containers:
      - image: skaliarman/in-cluster
        name: api-server
        ports:
        - containerPort: 8080
      serviceAccountName: xyz
        